source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

# If you want to use GitHub Pages, uncomment the line below.
gem "github-pages", "~> 229", group: :jekyll_plugins

# If you need additional gems, specify them here:
gem "uri", "~> 0.13"
gem "net-http", "~> 0.4"
gem "faraday", "~> 2.9"
gem "nokogiri", "~> 1.16"

# This is for ensuring webrick is included, required for Ruby 3.0 and later
gem "webrick", "~> 1.7"

# Environment variables for Jekyll
gem "jekyll-environment-variables"